import fs from "node:fs";
import path from "node:path";
import { describe, expect, it } from "vitest";

describe("truth-map audit route", () => {
  it("keeps an isolated, dynamic proposal-only route", () => {
    const page = fs.readFileSync(path.join(process.cwd(), "src", "app", "truth-map", "page.tsx"), "utf8");
    const runtime = fs.readFileSync(path.join(process.cwd(), "src", "app", "truth-map", "runtimeConfig.ts"), "utf8");
    expect(page).toContain('export const dynamic = "force-dynamic";');
    expect(page).toContain('countriesUrl="/api/truth-map/countries"');
    expect(page).toContain('usStatesUrl="/api/truth-map/us-states"');
    expect(runtime).toContain('dataSource: "FINAL_307_RECONCILIATION_PROPOSAL"');
    expect(runtime).toContain('mapRuntime: "active"');
  });

  it("uses the reconciled display core as the public map without production Social or AI", () => {
    const root = fs.readFileSync(path.join(process.cwd(), "src", "app", "page.tsx"), "utf8");
    const currentMap = fs.readFileSync(path.join(process.cwd(), "src", "app", "new-map", "page.tsx"), "utf8");
    const localRoot = fs.readFileSync(path.join(process.cwd(), "src", "app", "_components", "LocalPublicMapRoot.tsx"), "utf8");
    const runtime = fs.readFileSync(path.join(process.cwd(), "src", "app", "truth-map", "runtimeConfig.ts"), "utf8");
    const staticPayload = fs.readFileSync(path.join(process.cwd(), "src", "truth-map", "staticTruthMap.ts"), "utf8");
    const nextConfig = fs.readFileSync(path.join(process.cwd(), "next.config.ts"), "utf8");
    expect(root).toContain("TruthMapRoot");
    expect(root).toContain('presentation="public"');
    expect(root).toContain('countriesUrl: "/api/public-map/countries"');
    expect(root).toContain('usStatesUrl: "/api/public-map/us-states"');
    expect(root).not.toContain("getSocialRuntimeConfig");
    expect(root).not.toContain("MapGeoDock");
    expect(root).not.toContain("TruthMapSocialPanel");
    expect(root).toContain("isLocalAuditHost");
    expect(root).toContain("LocalPublicMapRoot");
    expect(root).toContain('showPublicMapNotice={false}');
    expect(runtime).toContain("getStaticTruthMapRuntimeMeta");
    expect(runtime).not.toContain("truthMapSource");
    expect(staticPayload).not.toContain("truthMapSource");
    expect(nextConfig).not.toContain("wiki-truth-307-final-reconciliation.json");
    expect(localRoot).toContain("MapGeoDock");
    expect(localRoot).not.toContain("TruthMapSocialPanel");
    expect(currentMap).toContain("permanentRedirect(canonicalPublicMapTarget(resolvedSearchParams))");
    expect(currentMap).toContain("NewMapClientEntry");
  });

  it("uses the canonical Store Truth gate through separate public read adapters", () => {
    const mainMap = fs.readFileSync(path.join(process.cwd(), "src", "new-map", "MapRoot.tsx"), "utf8");
    const mapFactory = fs.readFileSync(path.join(process.cwd(), "src", "new-map", "createMap.ts"), "utf8");
    const storeLayer = fs.readFileSync(path.join(process.cwd(), "src", "new-map", "stores", "StoreLayer.ts"), "utf8");
    const overlayPlacement = fs.readFileSync(path.join(process.cwd(), "src", "new-map", "overlayLayerPlacement.ts"), "utf8");
    const truthMap = fs.readFileSync(path.join(process.cwd(), "src", "truth-map", "TruthMapRoot.tsx"), "utf8");
    const auditRoot = fs.readFileSync(path.join(process.cwd(), "src", "truth-map", "TruthMapAuditRoot.tsx"), "utf8");
    expect(mainMap).not.toContain("useStoreMapLayer");
    expect(mainMap).not.toContain("useSocialMapLayer");
    expect(storeLayer).toContain('"/api/truth-map/stores"');
    expect(storeLayer).toContain('"/api/truth-map/stores/summary"');
    expect(storeLayer).toContain('"/api/public-map/stores"');
    expect(storeLayer).toContain('"/api/public-map/stores/summary"');
    expect(storeLayer).toContain("PUBLIC_STORE_MAP_LAYER_ENDPOINTS");
    expect(storeLayer).toContain('"icon-image": STORE_MARKER_ICON_ID');
    expect(storeLayer).toContain('"icon-image": STORE_GEO_SUMMARY_ICON_ID');
    expect(storeLayer).toContain('"icon-anchor": "right"');
    expect(storeLayer).toContain('"text-anchor": "left"');
    expect(storeLayer).toContain('"text-offset": [0.45, 0]');
    expect(storeLayer).toContain('"text-halo-width": 2');
    expect(storeLayer).toContain('"icon-ignore-placement": true');
    expect(storeLayer).toContain('"text-ignore-placement": true');
    expect(storeLayer).toContain("findOverlayInsertionBeforeId");
    expect(storeLayer).toContain("moveEarlyNativeLabelsAboveOverlays");
    expect(overlayPlacement).toContain("final native geometry");
    expect(overlayPlacement).toContain('layer.type !== "symbol"');
    expect(overlayPlacement).toContain("map.moveLayer(layer.id, beforeId)");
    expect(storeLayer).toContain('"icon-size": ["interpolate", ["linear"], ["zoom"], 9, 1.02, 12, 1.17, 15, 1.35]');
    expect(storeLayer).toContain('"icon-allow-overlap": true');
    expect(storeLayer).toContain('"icon-ignore-placement": true');
    expect(storeLayer).toContain('"icon-rotation-alignment": "viewport"');
    expect(storeLayer).toContain('"icon-pitch-alignment": "viewport"');
    expect(storeLayer).toContain('"text-allow-overlap": true');
    expect(storeLayer).toContain('"text-ignore-placement": true');
    expect(storeLayer).not.toContain('"circle-radius": ["interpolate", ["linear"], ["get", "count"]');
    expect(storeLayer).toContain('sdf: false');
    expect(storeLayer).toContain('type: "symbol"');
    expect(fs.readFileSync(path.join(process.cwd(), "public", "cannabis-store-leaf.svg"), "utf8")).toContain("<svg");
    expect(fs.readFileSync(path.join(process.cwd(), "public", "cannabis-store-summary-shop.svg"), "utf8")).toContain("<svg");
    expect(truthMap).toContain("useStoreMapLayer");
    expect(truthMap).toContain("publicPresentation ? PUBLIC_STORE_MAP_LAYER_ENDPOINTS : undefined");
    expect(mapFactory).toContain("renderWorldCopies: true");
    expect(truthMap).not.toContain("runtime.map.setRenderWorldCopies(false)");
    expect(truthMap).toContain("getStoreGeoSummaryCount");
    expect(truthMap).toContain('data-testid="truth-map-store-control"');
    expect(truthMap).toContain('data-store-layer-enabled={String(storesEnabled)}');
    expect(truthMap).not.toContain("TruthMapAuditSocialLayer");
    expect(truthMap).not.toContain("TruthMapSocialPanel");
    expect(truthMap).not.toContain("MapGeoDock");
    expect(auditRoot).toContain("TruthMapAuditSocialLayer");
    expect(auditRoot).toContain("TruthMapSocialPanel");
    expect(auditRoot).toContain("MapGeoDock");
    expect(truthMap).toContain('data-testid="truth-map-legal-evidence-guide"');
    expect(truthMap).toContain("✅ GREEN: verified lawful access");
    expect(truthMap).toContain("UNKNOWN is never presented as a confirmed prohibition");
    expect(truthMap).toContain("UnifiedSeoStatusPanel");
    expect(truthMap).toContain("onOpenDetails={handleOpenDetails}");
    expect(truthMap).toContain("showPublicMapNotice");
    expect(truthMap).toContain("publicLocalDock");
    expect(truthMap).toContain("AsciiOverlay");
    expect(truthMap).toContain("bindAsciiMapTriggers");
    expect(truthMap).toContain('surfaceTestId={publicPresentation ? "public-map-canvas" : "truth-map-canvas"}');
    expect(truthMap).not.toContain("MapGeoDock");
  });

  it("keeps the Social Chat surface on the audit route only", () => {
    const auditPage = fs.readFileSync(path.join(process.cwd(), "src", "app", "truth-map", "page.tsx"), "utf8");
    const mainMap = fs.readFileSync(path.join(process.cwd(), "src", "new-map", "MapRoot.tsx"), "utf8");
    const currentMap = fs.readFileSync(path.join(process.cwd(), "src", "app", "new-map", "page.tsx"), "utf8");
    const socialPanel = fs.readFileSync(path.join(process.cwd(), "src", "truth-map", "TruthMapSocialPanel.tsx"), "utf8");
    const socialLayer = fs.readFileSync(path.join(process.cwd(), "src", "new-map", "social", "SocialLayer.ts"), "utf8");
    expect(auditPage).toContain("getSocialRuntimeConfig");
    expect(mainMap).not.toContain("TruthMapSocialPanel");
    expect(currentMap).not.toContain("getSocialRuntimeConfig");
    expect(socialPanel).toContain("DURABLE_SOCIAL_STORAGE_REQUIRED");
    expect(socialPanel).toContain("disabled");
    expect(socialPanel).toContain("truth-map-social-map-area-focus");
    expect(socialPanel).toContain("SOCIAL_MAP_ACTIVITY_INVALIDATED_EVENT");
    expect(socialLayer).toContain("SOCIAL_MAP_ACTIVITY_SELECTED_EVENT");
    expect(socialLayer).toContain("SOCIAL_MAP_ACTIVITY_INVALIDATED_EVENT");
    expect(socialLayer).toContain("geoCell: item.geoCell");
    expect(socialLayer).toContain('"/social-discussion-chat.svg"');
    expect(socialLayer).toContain('15, ["interpolate", ["linear"], ["get", "activeDiscussionCount"], 1, 1.45, 10, 1.55, 100, 1.65]');
    expect(socialLayer).toContain('"text-size": ["interpolate", ["linear"], ["zoom"], 9, 12, 12, 13, 15, 14]');
    expect(socialLayer).toContain("findOverlayInsertionBeforeId");
    expect(socialLayer).toContain('"icon-rotation-alignment": "viewport"');
    expect(socialLayer).toContain('"icon-pitch-alignment": "viewport"');
    expect(socialLayer).toContain("sdf: false");
    expect(socialLayer).not.toContain('"icon-color": "#c026d3"');
    expect(socialLayer).not.toContain('"/cannabis-store-leaf.svg"');
    const socialIcon = fs.readFileSync(path.join(process.cwd(), "public", "social-discussion-chat.svg"), "utf8");
    const storeIcon = fs.readFileSync(path.join(process.cwd(), "public", "cannabis-store-leaf.svg"), "utf8");
    expect(socialIcon).toContain("<svg");
    expect(socialIcon).toContain('fill="#c026d3"');
    expect(socialIcon).toContain('stroke="#fff"');
    expect(storeIcon).toContain('fill="#16a34a"');
    expect(storeIcon).not.toContain('stroke=');
    expect(socialIcon).not.toBe(storeIcon);
  });

  it("keeps the public and audit display maps at the verified local-store zoom ceiling", () => {
    const page = fs.readFileSync(path.join(process.cwd(), "src", "app", "truth-map", "page.tsx"), "utf8");
    const truthMap = fs.readFileSync(path.join(process.cwd(), "src", "truth-map", "TruthMapRoot.tsx"), "utf8");
    const createMap = fs.readFileSync(path.join(process.cwd(), "src", "new-map", "createMap.ts"), "utf8");
    const currentMap = fs.readFileSync(path.join(process.cwd(), "src", "app", "new-map", "page.tsx"), "utf8");
    expect(page).toContain("readBoundedNumber(resolvedSearchParams?.zoom, 0, 15)");
    expect(truthMap).toContain("runtime.map.setMaxZoom(15)");
    expect(createMap).toContain("maxZoom: 14");
    expect(currentMap).toContain("readBoundedNumber(resolvedSearchParams?.zoom, 0, 14)");
  });

  it("keeps QA popup selection inside the complete route-local reconciliation datasets", () => {
    const truthMap = fs.readFileSync(path.join(process.cwd(), "src", "truth-map", "TruthMapRoot.tsx"), "utf8");
    expect(truthMap).toContain("fetchTruthMapCollection(countriesUrl)");
    expect(truthMap).toContain("fetchTruthMapCollection(usStatesUrl)");
    expect(truthMap).not.toContain("TRUTH_MAP_COLLECTION_CHUNKS_V1");
    expect(truthMap).not.toContain("truth_map_dataset_chunk_fetch");
    expect(truthMap).toContain("countries.features.find");
    expect(truthMap).toContain("usStates.features.find");
    expect(truthMap).toContain("openGeo: async (geo)");
  });
});
