#!/usr/bin/env bash
set -euo pipefail

if [ "${OFFLINE:-0}" = "1" ]; then
  FETCH_NETWORK=0
  NETWORK=0
  ALLOW_NETWORK=0
  WIKI_OFFLINE_OK=1
  ALLOW_WIKI_OFFLINE=1
  WIKI_REFRESH_ENABLE=0
  WIKI_CACHE_ONLY=1
  export FETCH_NETWORK NETWORK ALLOW_NETWORK WIKI_OFFLINE_OK ALLOW_WIKI_OFFLINE WIKI_REFRESH_ENABLE WIKI_CACHE_ONLY
fi
